=== kblack37/verigames/flash/TrafficJamFinal/world.dtd
<!ELEMENT world (level*)>
 <!ELEMENT level (linked-edges,boards)>
  <!ELEMENT linked-edges (edge-set*)>
   <!ELEMENT edge-set (edgeref*)>
    <!ELEMENT edgeref EMPTY>
     <!ATTLIST edgeref id IDREF #REQUIRED>
  <!ELEMENT boards (board*)>
   <!ELEMENT board (node*,edge*)>
    <!ATTLIST board name ID #REQUIRED>
    <!ELEMENT node (input,output)>
     <!ATTLIST node kind (INCOMING|OUTGOING|SPLIT|NULL_TEST|MERGE|START_WHITE_BALL|START_BLACK_BALL|START_NO_BALL|END|SUBNETWORK|CONNECT) #REQUIRED>
     <!ATTLIST node id ID #REQUIRED>
     <!ATTLIST node name IDREF #IMPLIED>
     <!ELEMENT input (port*)>
     <!ELEMENT output (port*)>
      <!ELEMENT port EMPTY>
       <!ATTLIST port num CDATA #REQUIRED>
       <!ATTLIST port edge IDREF #REQUIRED>
    <!ELEMENT edge (from,to)>
     <!ATTLIST edge var CDATA #IMPLIED>
     <!ATTLIST edge pinch (true|false) #REQUIRED>
     <!ATTLIST edge width (wide|narrow) #REQUIRED>
     <!ATTLIST edge id ID #REQUIRED>
     <!ELEMENT from (noderef)>
     <!ELEMENT to (noderef)>
      <!ELEMENT noderef EMPTY>
       <!ATTLIST noderef id IDREF #REQUIRED>
       <!ATTLIST noderef port CDATA #REQUIRED>

=== kblack37/verigames/flash/TrafficJamFinal/level.with.world.xml
<?xml version="1.0"?>
<!DOCTYPE world SYSTEM "world.dtd">
<world>
<level name="Chute">
 <linked-edges>
  <edge-set>
   <edgeref id="e115"/>
   <edgeref id="e117"/>
  </edge-set>
  <edge-set>
   <edgeref id="e142"/>
   <edgeref id="e143"/>
   <edgeref id="e141"/>
  </edge-set>
  <edge-set>
   <edgeref id="e158"/>
   <edgeref id="e157"/>
   <edgeref id="e159"/>
  </edge-set>
  <edge-set>
   <edgeref id="e200"/>
   <edgeref id="e201"/>
   <edgeref id="e202"/>
   <edgeref id="e114"/>
   <edgeref id="e197"/>
   <edgeref id="e173"/>
   <edgeref id="e176"/>
   <edgeref id="e175"/>
   <edgeref id="e174"/>
   <edgeref id="e169"/>
   <edgeref id="e162"/>
   <edgeref id="e153"/>
   <edgeref id="e146"/>
   <edgeref id="e135"/>
   <edgeref id="e134"/>
   <edgeref id="e136"/>
  </edge-set>
  <edge-set>
   <edgeref id="e203"/>
   <edgeref id="e204"/>
   <edgeref id="e205"/>
   <edgeref id="e130"/>
   <edgeref id="e190"/>
   <edgeref id="e191"/>
   <edgeref id="e178"/>
   <edgeref id="e177"/>
   <edgeref id="e170"/>
   <edgeref id="e163"/>
   <edgeref id="e154"/>
   <edgeref id="e147"/>
   <edgeref id="e137"/>
   <edgeref id="e129"/>
   <edgeref id="e128"/>
  </edge-set>
  <edge-set>
   <edgeref id="e206"/>
   <edgeref id="e207"/>
   <edgeref id="e208"/>
   <edgeref id="e132"/>
   <edgeref id="e193"/>
   <edgeref id="e194"/>
   <edgeref id="e179"/>
   <edgeref id="e180"/>
   <edgeref id="e171"/>
   <edgeref id="e164"/>
   <edgeref id="e155"/>
   <edgeref id="e148"/>
   <edgeref id="e138"/>
   <edgeref id="e123"/>
   <edgeref id="e133"/>
   <edgeref id="e124"/>
   <edgeref id="e122"/>
   <edgeref id="e121"/>
   <edgeref id="e125"/>
   <edgeref id="e131"/>
  </edge-set>
  <edge-set>
   <edgeref id="e209"/>
   <edgeref id="e210"/>
   <edgeref id="e211"/>
   <edgeref id="e126"/>
   <edgeref id="e198"/>
   <edgeref id="e183"/>
   <edgeref id="e184"/>
   <edgeref id="e182"/>
   <edgeref id="e181"/>
   <edgeref id="e172"/>
   <edgeref id="e165"/>
   <edgeref id="e152"/>
   <edgeref id="e150"/>
   <edgeref id="e151"/>
   <edgeref id="e145"/>
   <edgeref id="e144"/>
   <edgeref id="e139"/>
  </edge-set>
  <edge-set>
   <edgeref id="e212"/>
   <edgeref id="e213"/>
   <edgeref id="e214"/>
   <edgeref id="e127"/>
   <edgeref id="e199"/>
   <edgeref id="e166"/>
   <edgeref id="e167"/>
   <edgeref id="e168"/>
   <edgeref id="e160"/>
   <edgeref id="e161"/>
   <edgeref id="e156"/>
   <edgeref id="e149"/>
   <edgeref id="e140"/>
  </edge-set>
  <edge-set>
   <edgeref id="e216"/>
   <edgeref id="e217"/>
   <edgeref id="e218"/>
   <edgeref id="e219"/>
  </edge-set>
  <edge-set>
   <edgeref id="e224"/>
   <edgeref id="e225"/>
  </edge-set>
  <edge-set>
   <edgeref id="e226"/>
   <edgeref id="e227"/>
  </edge-set>
  <edge-set>
   <edgeref id="e229"/>
   <edgeref id="e230"/>
  </edge-set>
  <edge-set>
   <edgeref id="e116"/>
  </edge-set>
  <edge-set>
   <edgeref id="e118"/>
  </edge-set>
  <edge-set>
   <edgeref id="e119"/>
  </edge-set>
  <edge-set>
   <edgeref id="e120"/>
  </edge-set>
  <edge-set>
   <edgeref id="e185"/>
  </edge-set>
  <edge-set>
   <edgeref id="e186"/>
  </edge-set>
  <edge-set>
   <edgeref id="e188"/>
  </edge-set>
  <edge-set>
   <edgeref id="e187"/>
  </edge-set>
  <edge-set>
   <edgeref id="e189"/>
  </edge-set>
  <edge-set>
   <edgeref id="e192"/>
  </edge-set>
  <edge-set>
   <edgeref id="e195"/>
  </edge-set>
  <edge-set>
   <edgeref id="e196"/>
  </edge-set>
  <edge-set>
   <edgeref id="e215"/>
  </edge-set>
  <edge-set>
   <edgeref id="e220"/>
  </edge-set>
  <edge-set>
   <edgeref id="e221"/>
  </edge-set>
  <edge-set>
   <edgeref id="e222"/>
  </edge-set>
  <edge-set>
   <edgeref id="e223"/>
  </edge-set>
  <edge-set>
   <edgeref id="e228"/>
  </edge-set>
  <edge-set>
   <edgeref id="e231"/>
  </edge-set>
 </linked-edges>
 <boards>
  <board name="Chute.constructor">
   <node kind="INCOMING" id="n66">
    <input>
    </input>
    <output>
     <port num="0" edge="e114"/>
     <port num="1" edge="e115"/>
     <port num="2" edge="e121"/>
    </output>
   </node>
   <node kind="OUTGOING" id="n67">
    <input>
     <port num="0" edge="e114"/>
     <port num="1" edge="e130"/>
     <port num="2" edge="e132"/>
     <port num="3" edge="e126"/>
     <port num="4" edge="e127"/>
     <port num="5" edge="e125"/>
    </input>
    <output>
    </output>
   </node>
   <node kind="SPLIT" id="n68">
    <input>
     <port num="0" edge="e115"/>
    </input>
    <output>
     <port num="0" edge="e118"/>
     <port num="1" edge="e116"/>
    </output>
   </node>
   <node kind="MERGE" id="n69">
    <input>
     <port num="0" edge="e120"/>
     <port num="1" edge="e116"/>
    </input>
    <output>
     <port num="0" edge="e117"/>
    </output>
   </node>
   <node kind="END" id="n70">
    <input>
     <port num="0" edge="e117"/>
    </input>
    <output>
    </output>
   </node>
   <node kind="SPLIT" id="n71">
    <input>
     <port num="0" edge="e118"/>
    </input>
    <output>
     <port num="0" edge="e120"/>
     <port num="1" edge="e119"/>
    </output>
   </node>
   <node kind="END" id="n72">
    <input>
     <port num="0" edge="e119"/>
    </input>
    <output>
    </output>
   </node>
   <node kind="SPLIT" id="n73">
    <input>
     <port num="0" edge="e121"/>
    </input>
    <output>
     <port num="0" edge="e122"/>
     <port num="1" edge="e123"/>
    </output>
   </node>
   <node kind="MERGE" id="n74">
    <input>
     <port num="0" edge="e122"/>
     <port num="1" edge="e124"/>
    </input>
    <output>
     <port num="0" edge="e125"/>
    </output>
   </node>
   <node kind="SPLIT" id="n75">
    <input>
     <port num="0" edge="e123"/>
    </input>
    <output>
     <port num="0" edge="e133"/>
     <port num="1" edge="e124"/>
    </output>
   </node>
   <node kind="START_BLACK_BALL" id="n76">
    <input>
    </input>
    <output>
     <port num="0" edge="e126"/>
    </output>
   </node>
   <node kind="START_BLACK_BALL" id="n77">
    <input>
    </input>
    <output>
     <port num="0" edge="e127"/>
    </output>
   </node>
   <node kind="START_WHITE_BALL" id="n78">
    <input>
    </input>
    <output>
     <port num="0" edge="e128"/>
    </output>
   </node>
   <node kind="START_WHITE_BALL" id="n79">
    <input>
    </input>
    <output>
     <port num="0" edge="e129"/>
    </output>
   </node>
   <node kind="MERGE" id="n80">
    <input>
     <port num="0" edge="e128"/>
     <port num="1" edge="e129"/>
    </input>
    <output>
     <port num="0" edge="e130"/>
    </output>
   </node>
   <node kind="START_NO_BALL" id="n81">
    <input>
    </input>
    <output>
     <port num="0" edge="e131"/>
    </output>
   </node>
   <node kind="MERGE" id="n82">
    <input>
     <port num="0" edge="e131"/>
     <port num="1" edge="e133"/>
    </input>
    <output>
     <port num="0" edge="e132"/>
    </output>
   </node>
   <edge var="name" pinch="false" width="wide" id="e114">
    <from>
     <noderef id="n66" port="0"/>
    </from>
    <to>
     <noderef id="n67" port="0"/>
    </to>
   </edge>
   <edge var="aux" pinch="false" width="wide" id="e115">
    <from>
     <noderef id="n66" port="1"/>
    </from>
    <to>
     <noderef id="n68" port="0"/>
    </to>
   </edge>
   <edge var="aux" pinch="false" width="wide" id="e116">
    <from>
     <noderef id="n68" port="1"/>
    </from>
    <to>
     <noderef id="n69" port="1"/>
    </to>
   </edge>
   <edge var="aux" pinch="false" width="wide" id="e117">
    <from>
     <noderef id="n69" port="0"/>
    </from>
    <to>
     <noderef id="n70" port="0"/>
    </to>
   </edge>
   <edge var="aux" pinch="false" width="narrow" id="e118">
    <from>
     <noderef id="n68" port="0"/>
    </from>
    <to>
     <noderef id="n71" port="0"/>
    </to>
   </edge>
   <edge var="aux" pinch="true" width="narrow" id="e119">
    <from>
     <noderef id="n71" port="1"/>
    </from>
    <to>
     <noderef id="n72" port="0"/>
    </to>
   </edge>
   <edge var="aux" pinch="false" width="narrow" id="e120">
    <from>
     <noderef id="n71" port="0"/>
    </from>
    <to>
     <noderef id="n69" port="0"/>
    </to>
   </edge>
   <edge var="aux.elts" pinch="false" width="wide" id="e121">
    <from>
     <noderef id="n66" port="2"/>
    </from>
    <to>
     <noderef id="n73" port="0"/>
    </to>
   </edge>
   <edge var="aux.elts" pinch="false" width="wide" id="e122">
    <from>
     <noderef id="n73" port="0"/>
    </from>
    <to>
     <noderef id="n74" port="0"/>
    </to>
   </edge>
   <edge var="aux.elts" pinch="false" width="wide" id="e123">
    <from>
     <noderef id="n73" port="1"/>
    </from>
    <to>
     <noderef id="n75" port="0"/>
    </to>
   </edge>
   <edge var="aux.elts" pinch="false" width="wide" id="e124">
    <from>
     <noderef id="n75" port="1"/>
    </from>
    <to>
     <noderef id="n74" port="1"/>
    </to>
   </edge>
   <edge var="aux.elts" pinch="false" width="wide" id="e125">
    <from>
     <noderef id="n74" port="0"/>
    </from>
    <to>
     <noderef id="n67" port="5"/>
    </to>
   </edge>
   <edge var="start" pinch="false" width="wide" id="e126">
    <from>
     <noderef id="n76" port="0"/>
    </from>
    <to>
     <noderef id="n67" port="3"/>
    </to>
   </edge>
   <edge var="end" pinch="false" width="wide" id="e127">
    <from>
     <noderef id="n77" port="0"/>
    </from>
    <to>
     <noderef id="n67" port="4"/>
    </to>
   </edge>
   <edge var="auxiliaryChutes" pinch="false" width="wide" id="e128">
    <from>
     <noderef id="n78" port="0"/>
    </from>
    <to>
     <noderef id="n80" port="0"/>
    </to>
   </edge>
   <edge var="auxiliaryChutes" pinch="false" width="wide" id="e129">
    <from>
     <noderef id="n79" port="0"/>
    </from>
    <to>
     <noderef id="n80" port="1"/>
    </to>
   </edge>
   <edge var="auxiliaryChutes" pinch="false" width="wide" id="e130">
    <from>
     <noderef id="n80" port="0"/>
    </from>
    <to>
     <noderef id="n67" port="1"/>
    </to>
   </edge>
   <edge var="auxiliaryChutes.elts" pinch="false" width="wide" id="e131">
