=== kblack37/verigames/website/html/scripts/world.dtd
<!ELEMENT world (level*)>
 <!ATTLIST world version (1) #REQUIRED>
 <!ELEMENT level (linked-edges,boards)>
  <!ATTLIST level name CDATA #REQUIRED>
  <!ELEMENT linked-edges (edge-set*)>
   <!ELEMENT edge-set (stamp*,edgeref*)>
    <!ATTLIST edge-set id ID #REQUIRED>
    <!-- refers to a possible edge-set with whose color this edge-set can be stamped with -->
    <!ELEMENT stamp EMPTY>
     <!-- stamp ID must refer to an edge-set ID -->
     <!ATTLIST stamp id IDREF #REQUIRED>
     <!ATTLIST stamp active (true|false) #REQUIRED>
    <!ELEMENT edgeref EMPTY>
     <!ATTLIST edgeref id IDREF #REQUIRED>
  <!ELEMENT boards (board*)>
   <!ELEMENT board (node*,edge*)>
    <!ATTLIST board name ID #REQUIRED>
    <!ELEMENT node (input,output,layout?)>
     <!ATTLIST node kind (INCOMING|OUTGOING|SPLIT|GET|BALL_SIZE_TEST|MERGE|START_SMALL_BALL|START_LARGE_BALL|START_NO_BALL|START_PIPE_DEPENDENT_BALL|END|SUBBOARD|CONNECT) #REQUIRED>
     <!ATTLIST node id ID #REQUIRED>
     <!ATTLIST node name IDREF #IMPLIED>
     <!ELEMENT input (port*)>
     <!ELEMENT output (port*)>
      <!ELEMENT port EMPTY>
       <!ATTLIST port num CDATA #REQUIRED>
       <!ATTLIST port edge IDREF #REQUIRED>
     <!ELEMENT layout (x,y)>
      <!ELEMENT x (#PCDATA)>
      <!ELEMENT y (#PCDATA)>
    <!ELEMENT edge (from,to,edge-layout?)>
     <!ATTLIST edge description CDATA #REQUIRED>
     <!ATTLIST edge variableID CDATA #REQUIRED>
     <!ATTLIST edge pinch (true|false) #REQUIRED>
     <!ATTLIST edge width (wide|narrow) #REQUIRED>
     <!ATTLIST edge editable (true|false) #REQUIRED>
     <!ATTLIST edge buzzsaw (true|false) #REQUIRED>
     <!ATTLIST edge id ID #REQUIRED>
     <!ELEMENT from (noderef)>
     <!ELEMENT to (noderef)>
      <!ELEMENT noderef EMPTY>
       <!ATTLIST noderef id IDREF #REQUIRED>
       <!ATTLIST noderef port CDATA #REQUIRED>
     <!ELEMENT edge-layout (point,(point,point,point)*)>
      <!ELEMENT point (x,y)>

<!--

Node layout information:

   X and Y coordinates are integers starting at 0. (0,0) is the top left
   corner.

   Width:

      - MERGE, SPLIT, and NULL_TEST nodes have a width of 2. That is, a node to
      the right of a MERGE at (0,0) must be at (2,0) or to the right.

      - SUBNETWORK nodes have width = max(#incoming edges, #outgoing edges)

      - END nodes have a width of 1

   Height:

      - MERGE, SPLIT, START_XXX_BALL, and SUBNETWORK nodes have a height of 2.
      That is, a node below a SPLIT at (0,0) must be at (0,2) or below.

      - INCOMING nodes have a height of 1.

      - Nodes connected by an edge with pinch=true must have an extra y
      coordinate between them.

      - END nodes have a height of 1

================================================================================

Edge layout information:

   Edge layout is given in the form of a list of b-spline control points. The
   number of control points, x, will always be such that (x = 1 (mod 3)).
   Equivalently, (x mod 3) = 1, or x = 1 + 3n, where n is any nonnegative
   integer.
   
================================================================================

Requirements not enforced by the DTD:

   - All edges are contained in exactly one edge-set

   - All nodes that have kind SUBNETWORK must have a name attribute (and the
     name attribute is meaningless for other kinds of node)

   - variableID must be an integer

================================================================================

Misc:

   - NULL_TEST node:

      - Represents the branching that occurs when the variable represented by
      the input edge is tested against null.

      - Upon encountering this node, a small ball will roll to the output edge
      at port 0, and a large ball will roll to the output edge at port 1.

      - The output edge at port 0 must be narrow, and the output edge at port 1
      must be wide.
-->

=== kblack37/verigames/flash/TrafficJamFinal/get-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE world SYSTEM "world.dtd">
<world>
 <level name="Get">
  <linked-edges>
   <edge-set id="es1">
    <edgeref id="e71"/>
   </edge-set>
   <edge-set id="es2">
    <stamp id="es1" active="true"/>
    <edgeref id="e72"/>
   </edge-set>
   <edge-set id="es3">
    <edgeref id="e73"/>
   </edge-set>
   <edge-set id="es4">
    <stamp id="es1" active="false"/>
	<stamp id="es2" active="false"/>
	<stamp id="es5" active="true"/>
    <edgeref id="e74"/>
   </edge-set>
   <edge-set id="es5">
    <edgeref id="e75"/>
   </edge-set>
  </linked-edges>
  <boards>
   <board name="Get.Example">
    <node kind="INCOMING" id="n70">
     <input/>
     <output>
      <port num="0" edge="e71"/>
      <port num="1" edge="e72"/>
      <port num="2" edge="e73"/>
	  <port num="3" edge="e74"/>
     </output>
     <layout>
      <x>1.0</x>
      <y>0.00000</y>
     </layout>
    </node>
    <node kind="OUTGOING" id="n71">
     <input>
      <port num="0" edge="e75"/>
     </input>
     <output/>
     <layout>
      <x>3.0</x>
      <y>7.68000</y>
     </layout>
    </node>
    <node kind="GET" id="n72">
     <input>
      <port num="0" edge="e71"/>
	  <port num="1" edge="e72"/>
	  <port num="2" edge="e73"/>
	  <port num="3" edge="e74"/>
     </input>
     <output>
      <port num="0" edge="e75"/>
     </output>
     <layout>
      <x>1.0</x>
      <y>2.5</y>
     </layout>
    </node>
    <edge description="chute1" variableID="-1" pinch="true" width="wide" editable="true" id="e71" buzzsaw="false">
     <from>
      <noderef id="n70" port="0"/>
     </from>
     <to>
      <noderef id="n72" port="0"/>
     </to>
     <edge-layout>
      <point>
       <x>1.5</x>
       <y>0.0</y>
      </point>
      <point>
       <x>1.5</x>
       <y>0.0</y>
      </point>
      <point>
       <x>1.5</x>
       <y>2.5</y>
      </point>
      <point>
       <x>1.5</x>
       <y>2.5</y>
      </point>
     </edge-layout>
    </edge>
    <edge description="chute2" variableID="-1" pinch="false" width="narrow" editable="true" id="e72" buzzsaw="false">
     <from>
      <noderef id="n70" port="1"/>
     </from>
     <to>
      <noderef id="n72" port="1"/>
     </to>
     <edge-layout>
      <point>
       <x>2.5</x>
       <y>0.0</y>
      </point>
      <point>
       <x>2.5</x>
       <y>0.0</y>
      </point>
      <point>
       <x>2.5</x>
       <y>2.5</y>
      </point>
      <point>
       <x>2.5</x>
       <y>2.5</y>
      </point>
     </edge-layout>
    </edge>
	<edge description="chute3" variableID="-1" pinch="false" width="narrow" editable="true" id="e73" buzzsaw="false">
     <from>
      <noderef id="n70" port="2"/>
     </from>
     <to>
      <noderef id="n72" port="2"/>
     </to>
     <edge-layout>
      <point>
       <x>3.5</x>
       <y>0.0</y>
      </point>
      <point>
       <x>3.5</x>
       <y>0.0</y>
      </point>
      <point>
       <x>3.5</x>
       <y>2.5</y>
      </point>
      <point>
       <x>3.5</x>
       <y>2.5</y>
      </point>
     </edge-layout>
    </edge>
	<edge description="chute4" variableID="-1" pinch="false" width="narrow" editable="true" id="e74" buzzsaw="false">
     <from>
      <noderef id="n70" port="3"/>
     </from>
     <to>
      <noderef id="n72" port="3"/>
     </to>
     <edge-layout>
      <point>
       <x>4.5</x>
       <y>0.0</y>
      </point>
      <point>
       <x>4.5</x>
       <y>0.0</y>
      </point>
      <point>
       <x>4.5</x>
       <y>2.5</y>
      </point>
      <point>
       <x>4.5</x>
       <y>2.5</y>
      </point>
     </edge-layout>
    </edge>
	<edge description="chute5" variableID="-1" pinch="false" width="wide" editable="true" id="e75" buzzsaw="false">
     <from>
      <noderef id="n72" port="0"/>
     </from>
     <to>
      <noderef id="n71" port="0"/>
     </to>
     <edge-layout>
      <point>
       <x>3.5</x>
       <y>3.96</y>
      </point>
      <point>
       <x>3.5</x>
       <y>3.96</y>
      </point>
      <point>
       <x>3.5</x>
       <y>7.68</y>
      </point>
      <point>
       <x>3.5</x>
       <y>7.68</y>
      </point>
     </edge-layout>
    </edge>
   </board>
  </boards>
 </level>
</world>

=== kblack37/verigames/flash/TrafficJamFinal/SampleWorlds/StraightWorld.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE world SYSTEM "world.dtd">
<world version="1">
	<level name="Simple">
		<linked-edges>
			<edge-set id="Simple0">
				<stamp id="Simple1" active="true" />
				<stamp id="Simple2" active="true" />
				<edgeref id="e0" />
			</edge-set>
			<edge-set id="Simple1">
				<stamp id="Simple0" active="true" />
				<stamp id="Simple2" active="true" />
				<edgeref id="e1" />
			</edge-set>
			<edge-set id="Simple2">
				<stamp id="Simple0" active="true" />
				<stamp id="Simple2" active="true" />
				<edgeref id="e2" />
			</edge-set>
		</linked-edges>
		<boards>
			<board name="SimpleMain">
				<node kind="START_PIPE_DEPENDENT_BALL" id="n1">
					<input />
					<output>
						<port num="0" edge="e0" />
					</output>
					<layout>
						<x>4</x>
						<y>1</y>
					</layout>
				</node>

				<node kind="CONNECT" id="n2">
					<input>
						<port num="0" edge="e0" />
						</input>
					<output>
						<port num="0" edge="e1" />
					</output>
					<layout>
						<x>4</x>
						<y>5</y>
					</layout>
				</node>
				<node kind="END" id="n3">
					<input>
						<port num="0" edge="e1" />
					</input>
					<output />
					<layout>
						<x>4</x>
						<y>7</y>
					</layout>
				</node>
				<edge description="foo" variableID="1" pinch="false" width="wide"
					editable="true" id="e0" buzzsaw="false">
					<from>
						<noderef id="n1" port="0" />
					</from>
					<to>
						<noderef id="n2" port="0" />
					</to>
					<edge-layout>
						<point>
							<x>4</x>
							<y>1</y>
						</point>
						<point>
							<x>4</x>
							<y>5</y>
						</point>
					</edge-layout>
				</edge>
				<edge description="this" variableID="-1" pinch="false" width="narrow"
					editable="true" id="e1" buzzsaw="false">
					<from>
						<noderef id="n2" port="0" />
					</from>
					<to>
						<noderef id="n3" port="0" />
					</to>
					<edge-layout>
						<point>
							<x>4</x>
							<y>5</y>
						</point>
						<point>
							<x>4</x>
							<y>7</y>
						</point>
					</edge-layout>
				</edge>
			</board>
		</boards>
	</level>
</world>

=== kblack37/verigames/java/Translation/test/verigames/layout/GETLayoutTest.expected.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE world SYSTEM "http://types.cs.washington.edu/verigames/world.dtd">
<world version="3">
 <linked-varIDs/>
 <level name="GetTestLevel">
  <boards>
   <board name="GetTestBoard">
    <node kind="INCOMING" id="n0">
     <input/>
     <output>
      <port num="0" edge="e1"/>
      <port num="1" edge="e2"/>
      <port num="2" edge="e3"/>
      <port num="3" edge="e4"/>
     </output>
     <layout>
      <x>0.0000000000</x>
      <y>0.0000000000</y>
     </layout>
    </node>
    <node kind="OUTGOING" id="n1">
     <input>
      <port num="0" edge="e5"/>
     </input>
     <output/>
     <layout>
      <x>0.0000000000</x>
      <y>7.68000</y>
     </layout>
    </node>
    <node kind="GET" id="n2">
     <input>
      <port num="0" edge="e1"/>
      <port num="1" edge="e2"/>
      <port num="2" edge="e3"/>
      <port num="3" edge="e4"/>
     </input>
     <output>
      <port num="0" edge="e5"/>
     </output>
     <layout>
      <x>0.0000000000</x>
      <y>1.95623</y>
     </layout>
    </node>
    <edge description="chute1" variableID="-1" pinch="false" width="narrow" editable="true" id="e1" buzzsaw="false">
     <from>
      <noderef id="n0" port="0"/>
     </from>
     <to>
      <noderef id="n2" port="0"/>
     </to>
     <edge-layout>
      <point>
       <x>0.50000</x>
       <y>0.0000000000</y>
      </point>
      <point>
       <x>0.50000</x>
       <y>0.95069</y>
      </point>
      <point>
       <x>0.50000</x>
       <y>1.27219</y>
      </point>
      <point>
       <x>0.50000</x>
       <y>1.95623</y>
      </point>
     </edge-layout>
    </edge>
    <edge description="chute2" variableID="-1" pinch="false" width="narrow" editable="true" id="e2" buzzsaw="false">
     <from>
      <noderef id="n0" port="1"/>
     </from>
     <to>
      <noderef id="n2" port="1"/>
     </to>
     <edge-layout>
      <point>
       <x>1.50000</x>
       <y>0.0000000000</y>
      </point>
      <point>
       <x>1.50000</x>
       <y>0.95069</y>
      </point>
      <point>
       <x>1.50000</x>
       <y>1.27219</y>
      </point>
      <point>
       <x>1.50000</x>
       <y>1.95623</y>
      </point>
     </edge-layout>
    </edge>
    <edge description="chute3" variableID="-1" pinch="false" width="narrow" editable="true" id="e3" buzzsaw="false">
     <from>
      <noderef id="n0" port="2"/>
     </from>
     <to>
      <noderef id="n2" port="2"/>
     </to>
     <edge-layout>
      <point>
       <x>2.50000</x>
       <y>0.0000000000</y>
      </point>
      <point>
       <x>2.50000</x>
       <y>0.95069</y>
      </point>
      <point>
       <x>2.50000</x>
       <y>1.27219</y>
      </point>
      <point>
       <x>2.50000</x>
       <y>1.95623</y>
      </point>
     </edge-layout>
    </edge>
    <edge description="chute4" variableID="-1" pinch="false" width="narrow" editable="true" id="e4" buzzsaw="false">
     <from>
      <noderef id="n0" port="3"/>
     </from>
     <to>
      <noderef id="n2" port="3"/>
     </to>
     <edge-layout>
      <point>
       <x>3.50000</x>
       <y>0.0000000000</y>
      </point>
      <point>
       <x>3.50000</x>
       <y>0.95069</y>
      </point>
      <point>
       <x>3.50000</x>
       <y>1.27219</y>
      </point>
      <point>
       <x>3.50000</x>
       <y>1.95623</y>
      </point>
     </edge-layout>
    </edge>
    <edge description="chute5" variableID="-1" pinch="false" width="narrow" editable="true" id="e5" buzzsaw="false">
     <from>
      <noderef id="n2" port="0"/>
     </from>
     <to>
      <noderef id="n1" port="0"/>
     </to>
     <edge-layout>
      <point>
       <x>0.50000</x>
       <y>3.41623</y>
      </point>
      <point>
       <x>0.50000</x>
       <y>5.38365</y>
      </point>
      <point>
       <x>0.50000</x>
       <y>6.11787</y>
      </point>
      <point>
       <x>0.50000</x>
       <y>7.68000</y>
      </point>
     </edge-layout>
    </edge>
   </board>
  </boards>
 </level>
</world>

=== kblack37/verigames/flash/TrafficJamFinal/exception.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE world SYSTEM "world.dtd">
<world>
 <level name="Placeholder">
  <linked-edges>
   <edge-set>
    <edgeref id="e1"/>
    <edgeref id="e2"/>
   </edge-set>
   <edge-set>
    <edgeref id="e3"/>
   </edge-set>
  </linked-edges>
  <boards>
   <board name="Placeholder">
    <node kind="INCOMING" id="n0">
     <input/>
     <output>
      <port num="0" edge="e1"/>
     </output>
     <layout>
      <x>0.00000</x>
      <y>0.00000</y>
     </layout>
    </node>
    <node kind="OUTGOING" id="n1">
     <input>
      <port num="0" edge="e2"/>
     </input>
     <output/>
     <layout>
      <x>0.44444</x>
      <y>7.68000</y>
     </layout>
    </node>
    <node kind="START_LARGE_BALL" id="n2">
     <input/>
     <output>
      <port num="0" edge="e3"/>
     </output>
     <layout>
      <x>0.88889</x>
      <y>1.14898</y>
     </layout>
    </node>
    <node kind="MERGE" id="n3">
     <input>
      <port num="0" edge="e1"/>
      <port num="1" edge="e3"/>
     </input>
     <output>
      <port num="0" edge="e2"/>
     </output>
     <layout>
      <x>0.44444</x>
      <y>4.41449</y>
     </layout>
    </node>
    <edge description="chute1" variableID="-1" pinch="false" width="narrow" editable="true" id="e1" buzzsaw="false">
     <from>
      <noderef id="n0" port="0"/>
     </from>
     <to>
      <noderef id="n3" port="0"/>
     </to>
     <edge-layout>
      <point>
       <x>0.50000</x>
       <y>0.00000</y>
      </point>
      <point>
       <x>0.50000</x>
       <y>2.50416</y>
      </point>
      <point>
       <x>0.94444</x>
       <y>5.47276</y>
      </point>
      <point>
       <x>0.94444</x>
       <y>5.47276</y>
      </point>
     </edge-layout>
    </edge>
    <edge description="chute1" variableID="-1" pinch="true" width="narrow" editable="true" id="e2" buzzsaw="false">
     <from>
      <noderef id="n3" port="0"/>
     </from>
     <to>
      <noderef id="n1" port="0"/>
     </to>
     <edge-layout>
      <point>
       <x>0.94444</x>
       <y>5.53323</y>
      </point>
      <point>
       <x>0.94444</x>
       <y>5.53323</y>
      </point>
      <point>
       <x>0.94444</x>
       <y>6.72574</y>
      </point>
      <point>
       <x>0.94444</x>
       <y>7.68000</y>
      </point>
     </edge-layout>
    </edge>
    <edge description="chute3" variableID="-1" pinch="false" width="narrow" editable="true" id="e3" buzzsaw="false">
     <from>
      <noderef id="n2" port="0"/>
     </from>
     <to>
      <noderef id="n3" port="1"/>
     </to>
     <edge-layout>
      <point>
       <x>1.38889</x>
       <y>2.26772</y>
      </point>
      <point>
       <x>1.38889</x>
       <y>2.26772</y>
      </point>
      <point>
       <x>0.94444</x>
       <y>5.47276</y>
      </point>
      <point>
       <x>0.94444</x>
       <y>5.47276</y>
      </point>
     </edge-layout>
    </edge>
   </board>
  </boards>
 </level>
</world>
